
findtopk: findtopk.c
	gcc -o findtopk findtopk.c

findtopk_mqueue: findtopk_mqueue.cpp
	gcc -o findtopk_mqueue findtopk_mqueue.cpp

findtopk_thread: findtopk_thread.c
	gcc -o findtopk_thread findtopk_thread.c -lpthread

